"""HTML template for self-contained audit pack export."""

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Audit Pack: {model_name}</title>
<style>
  :root {{
    --primary: #1a56db;
    --primary-light: #e8edfb;
    --success: #0e9f6e;
    --success-bg: #def7ec;
    --error: #e02424;
    --error-bg: #fde8e8;
    --warning: #e3a008;
    --warning-bg: #fdf6b2;
    --border: #e5e7eb;
    --bg: #f9fafb;
    --text: #111827;
    --text-secondary: #6b7280;
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    color: var(--text);
    background: var(--bg);
    line-height: 1.6;
    padding: 2rem;
    max-width: 960px;
    margin: 0 auto;
  }}
  h1 {{
    font-size: 1.75rem;
    margin-bottom: 0.25rem;
  }}
  h2 {{
    font-size: 1.25rem;
    margin: 2rem 0 1rem;
    padding-bottom: 0.5rem;
    border-bottom: 2px solid var(--primary);
    color: var(--primary);
  }}
  .subtitle {{
    color: var(--text-secondary);
    font-size: 0.9rem;
    margin-bottom: 1.5rem;
  }}
  table {{
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 1.5rem;
    background: #fff;
    border-radius: 8px;
    overflow: hidden;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
  }}
  th, td {{
    padding: 0.75rem 1rem;
    text-align: left;
    border-bottom: 1px solid var(--border);
  }}
  th {{
    background: var(--primary-light);
    font-weight: 600;
    font-size: 0.85rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }}
  tr:last-child td {{ border-bottom: none; }}
  .badge {{
    display: inline-block;
    padding: 0.2rem 0.6rem;
    border-radius: 9999px;
    font-size: 0.75rem;
    font-weight: 600;
    text-transform: uppercase;
  }}
  .badge-pass {{ background: var(--success-bg); color: var(--success); }}
  .badge-fail {{ background: var(--error-bg); color: var(--error); }}
  .badge-error {{ background: var(--error-bg); color: var(--error); }}
  .badge-warning {{ background: var(--warning-bg); color: var(--warning); }}
  .badge-info {{ background: var(--primary-light); color: var(--primary); }}
  .event-card {{
    background: #fff;
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 1rem;
    margin-bottom: 0.75rem;
    box-shadow: 0 1px 2px rgba(0,0,0,0.05);
  }}
  .event-card .action {{
    font-weight: 600;
    color: var(--primary);
  }}
  .event-card .meta {{
    color: var(--text-secondary);
    font-size: 0.85rem;
    margin-top: 0.25rem;
  }}
  .event-card .details {{
    font-size: 0.85rem;
    color: var(--text-secondary);
    margin-top: 0.25rem;
  }}
  footer {{
    margin-top: 3rem;
    padding-top: 1rem;
    border-top: 1px solid var(--border);
    color: var(--text-secondary);
    font-size: 0.8rem;
    text-align: center;
  }}
  .tree-container {{
    background: #fff;
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 1.5rem;
    margin-bottom: 1.5rem;
    font-family: "SF Mono", "Cascadia Code", Menlo, monospace;
    font-size: 0.85rem;
    line-height: 1.8;
  }}
  .tree-node {{ padding-left: 1.5rem; }}
  .tree-type {{ color: var(--text-secondary); font-size: 0.75rem; }}
  details {{ margin-bottom: 0.25rem; }}
  details summary {{ cursor: pointer; }}
</style>
</head>
<body>

<h1>{model_name}</h1>
<p class="subtitle">Audit Pack &mdash; Generated {generated_at}</p>

{executive_summary}

<h2>Model Card</h2>
<table>
  <tr><th>Field</th><th>Value</th></tr>
  <tr><td>Name</td><td>{model_name}</td></tr>
  <tr><td>Owner</td><td>{owner}</td></tr>
  <tr><td>Tier</td><td>{tier}</td></tr>
  <tr><td>Status</td><td>{model_status}</td></tr>
  <tr><td>Type</td><td>{model_type}</td></tr>
  <tr><td>Intended Purpose</td><td>{intended_purpose}</td></tr>
</table>

<h2>Version Details</h2>
<table>
  <tr><th>Field</th><th>Value</th></tr>
  <tr><td>Version</td><td>{version}</td></tr>
  <tr><td>Status</td><td>{version_status}</td></tr>
  <tr><td>Algorithm / Methodology</td><td>{methodology}</td></tr>
  <tr><td>Run Frequency</td><td>{run_frequency}</td></tr>
  <tr><td>Training Target</td><td>{training_target}</td></tr>
</table>

<h2>Component Tree</h2>
{component_tree_section}

<h2>Validation Results</h2>
{validation_section}

<h2>Audit Trail</h2>
{audit_trail_section}

<footer>
  Generated by model-ledger v{ledger_version} on {generated_at}
</footer>

</body>
</html>
"""

VALIDATION_PASS = (
    '<p><span class="badge badge-pass">PASS</span>'
    " All rules satisfied for profile"
    " <strong>{profile}</strong>.</p>\n"
)

VALIDATION_FAIL_HEADER = (
    '<p><span class="badge badge-fail">FAIL</span>'
    " Profile <strong>{profile}</strong>"
    " &mdash; {error_count} error(s),"
    " {warning_count} warning(s).</p>\n"
    "<table>\n"
    "  <tr><th>Rule</th><th>Severity</th>"
    "<th>Message</th><th>Suggestion</th></tr>\n"
    "{rows}\n"
    "</table>\n"
)

VIOLATION_ROW = """\
  <tr>
    <td>{rule_id}</td>
    <td><span class="badge badge-{severity_class}">{severity}</span></td>
    <td>{message}</td>
    <td>{suggestion}</td>
  </tr>"""

EVENT_CARD = """\
<div class="event-card">
  <div class="action">{action}</div>
  <div class="meta">{actor} &bull; {timestamp}{version_label}</div>
  <div class="details">{details}</div>
</div>
"""

COMPONENT_TREE_CSS = """\
  .tree-container {{
    background: #fff;
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 1.5rem;
    margin-bottom: 1.5rem;
    font-family: "SF Mono", "Cascadia Code", Menlo, monospace;
    font-size: 0.85rem;
    line-height: 1.8;
  }}
  .tree-node {{ padding-left: 1.5rem; }}
  .tree-label {{ color: var(--text); }}
  .tree-type {{ color: var(--text-secondary); font-size: 0.75rem; }}
  .tree-icon {{ margin-right: 0.3rem; }}
  details {{ margin-bottom: 0.5rem; }}
  details summary {{ cursor: pointer; font-weight: 600; }}
  details summary:hover {{ color: var(--primary); }}
"""

EXEC_SUMMARY_SECTION = """\
<div style="background: #fff; border: 1px solid var(--border); border-radius: 8px; padding: 1.5rem; margin-bottom: 2rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
  <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem;">
    <div>
      <div style="color: var(--text-secondary); font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em;">Risk Tier</div>
      <div style="font-size: 1.25rem; font-weight: 700; margin-top: 0.25rem;">{tier}</div>
    </div>
    <div>
      <div style="color: var(--text-secondary); font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em;">Model Type</div>
      <div style="font-size: 1.25rem; font-weight: 700; margin-top: 0.25rem;">{model_type}</div>
    </div>
    <div>
      <div style="color: var(--text-secondary); font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em;">Compliance Status</div>
      <div style="font-size: 1.25rem; font-weight: 700; margin-top: 0.25rem;">{compliance_summary}</div>
    </div>
    <div>
      <div style="color: var(--text-secondary); font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em;">Audit Events</div>
      <div style="font-size: 1.25rem; font-weight: 700; margin-top: 0.25rem;">{audit_count}</div>
    </div>
  </div>
</div>
"""
