"""LedgerBackend protocol — v0.3.0 storage interface."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from model_ledger.core.ledger_models import ModelRef, Snapshot, Tag


@runtime_checkable
class LedgerBackend(Protocol):
    def save_model(self, model: ModelRef) -> None: ...
    def get_model(self, model_hash: str) -> ModelRef | None: ...
    def get_model_by_name(self, name: str) -> ModelRef | None: ...
    def list_models(self, **filters: str) -> list[ModelRef]: ...
    def update_model(self, model: ModelRef) -> None: ...

    def append_snapshot(self, snapshot: Snapshot) -> None: ...
    def get_snapshot(self, snapshot_hash: str) -> Snapshot | None: ...
    def list_snapshots(self, model_hash: str, **filters: str) -> list[Snapshot]: ...
    def latest_snapshot(self, model_hash: str, tag: str | None = None) -> Snapshot | None: ...

    def set_tag(self, tag: Tag) -> None: ...
    def get_tag(self, model_hash: str, name: str) -> Tag | None: ...
    def list_tags(self, model_hash: str) -> list[Tag]: ...
