"""Backend protocol — the interface all storage backends must implement."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from model_ledger.core.models import AuditEvent, Model, ModelVersion


@runtime_checkable
class InventoryBackend(Protocol):
    def save_model(self, model: Model) -> None: ...
    def get_model(self, name: str) -> Model | None: ...
    def list_models(self) -> list[Model]: ...
    def save_version(self, model_name: str, version: ModelVersion) -> None: ...
    def get_version(self, model_name: str, version: str) -> ModelVersion | None: ...
    def list_versions(self, model_name: str) -> list[ModelVersion]: ...
    def force_save_version(self, model_name: str, version: ModelVersion) -> None: ...
    def append_audit_event(self, event: AuditEvent) -> None: ...
    def get_audit_log(self, model_name: str, version: str | None = None) -> list[AuditEvent]: ...
