# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Gitleaks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@44c470ffc35caa8b1eb3e8012ca53c2f9f815dc8 # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_CONFIG: .gitleaks.toml
